// This file overrides the built-in Python 3 runner
// 1.) Select Run->Run With->New Runner
// 2.) Copy&Paste the following code
// 3.) Save runner under .c9/runners/python3venv.run
// 4.) Select "python3venv.run" and click Run
// 5.) As Command select python file, e.g. /home/ubuntu/environment/python-ldap-test/random_users.py

// AWS Docs: http://docs.aws.amazon.com/console/cloud9/change-runner
// Builtin Runner Params: https://cloud9-sdk.readme.io/docs/runners 
// Blueprint: https://newbedev.com/configure-aws-cloud9-to-use-anaconda-python-environment
// Blueprint 2: https://stackoverflow.com/questions/33183992/cloud9-ide-to-run-python3-with-venv
{
  "script": [
    "if [ \"$debug\" == true ]; then ",
    "    $file_path/venv/bin/python -m ikp3db -ik_p=15471 -ik_cwd=$project_path \"$file\" $args",
    "else",
    "   $file_path/venv/bin/python \"$file\" $args",
    "fi",
    "checkExitCode() {",
    "    if [ $1 ] && [ \"$debug\" == true ]; then ",
    "        $file_path/venv/bin/python -m ikp3db 2>&1 | grep -q 'No module' && echo '",
    "    To use python debugger install ikpdb by running: ",
    "        source $file_path/venv/bin/activate",
    "        python3 -m pip install ikp3db;",
    "        deactivate",
    "        '",
    "    fi",
    "   return $1",
    "}",
    "checkExitCode $?"
  ],
  "python_version": "$file_path/venv/bin/python",
  "working_dir": "$project_path",
  "debugport": 15471,
  "$debugDefaultState": false,
  "debugger": "ikpdb",
  "selector": "^.*\\.(py)$",
  "env": {
    "PYTHONPATH": "$python_path"
  },
  "trackId": "$file_path/venv/bin/python"
}