variables:
  GITLAB_MIRROR_IMAGE_VERSION: "0.3.15"

  # Make sure the following protected variables are provided by the Gitlab CI Environment
  # CI_SERVER_HOST, e.g. "dfwpgitlab.sial.com"
  # GITMAGIC_USER_EMAIL, e.g. "admin-list@bssn-software.de"
  # GITMAGIC_USER_NAME, e.g. "bssnbot"
  # GITMAGIC_ACCESS_TOKEN, e.g. "DH..X"
  # KANIKO_REGISTRY_HOSTNAME

  # Make sure the following variables are provided by the Gitlab Shedule Operation
  # GITLAB_MIRROR_ADDRESS, e.g. "git-codecommit.eu-central-1.amazonaws.com/v1/repos/cci-git-mirror-iam"
  # GITLAB_MIRROR_USERNAME, e.g. "GitlabMirrorBot-at-673223924635"
  # GITLAB_MIRROR_PASSWORD, e.g. "aWg..U="

git-pull-conventional-remote-branches:
  stage: git-mirror-operations
  image:
    name: $KANIKO_REGISTRY_HOSTNAME/lab-solutions-devops/git-pull-conventional-remote-branches:$GITLAB_MIRROR_IMAGE_VERSION
  script:
  - echo "$KANIKO_REGISTRY_HOSTNAME/lab-solutions-devops/git-pull-conventional-remote-branches:$GITLAB_MIRROR_IMAGE_VERSION"
  - /bin/bash -c /git/apply.sh
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true" && $GITLAB_MIRROR_ADDRESS != null && $GITLAB_MIRROR_USERNAME != null && $GITLAB_MIRROR_PASSWORD != null

stages:
- git-mirror-operations
