variables:
   GITLAB_MIRROR_IMAGES_REPOSITORY: "lab-solutions-devops"
   GITLAB_MIRROR_IMAGES_VERSION: "0.3.15"

stages:
  - build 

.kaniko-build-template: &kaniko-build-template
  only:
    refs:
    - master
  stage: build
  image:
    name: docker.apps.bssn-software.de/base-images/gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  - |
    if [ -z "$KANIKO_REGISTRY_HOSTNAME" ]; 
      then
        echo "[WARNING] Script needs env var \"KANIKO_REGISTRY_HOSTNAME\" to be able to build fully qualified docker image"
      else
        echo "[INFO] env var KANIKO_REGISTRY_HOSTNAME is set"
    fi
  - |
    if [ -z "$KANIKO_REGISTRY_USER" ]; 
      then
        echo "[WARNING] Script needs env var \"KANIKO_REGISTRY_USER\" to be able to push to docker registry defined as KANIKO_REGISTRY_HOSTNAME"
      else
        echo "[INFO] env var KANIKO_REGISTRY_USER is set"
    fi
  - |
    if [ -z "$KANIKO_REGISTRY_PASSWORD" ]; 
    then
      echo "[WARNING] Script needs env var \"KANIKO_REGISTRY_PASSWORD\" to be able to push to docker registry defined as KANIKO_REGISTRY_HOSTNAME"
    else
      echo "[INFO] env var KANIKO_REGISTRY_PASSWORD is set"
    fi
  - |
    if [ "$CI_COMMIT_REF_PROTECTED" = false ]; then
      echo "[WARNING] Protected Variables are not applied to this pipeline" 
      echo "[WARNING] You'll have to set wildcard \"*-*_*-*\" for protected tags under project->settings->Repository->\"Protected Tags\" to use protected Environment Variables"
    fi
  - echo "{\"auths\":{\"$KANIKO_REGISTRY_HOSTNAME\":{\"auth\":\"$(echo -n $KANIKO_REGISTRY_USER:$KANIKO_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
  - echo "[INFO] GITLAB_USER_ID=$GITLAB_USER_ID, GITLAB_USER_LOGIN=$GITLAB_USER_LOGIN, GITLAB_USER_NAME=$GITLAB_USER_NAME, GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL"
  script:
  - | 
    IMAGE_NAME="$GITLAB_MIRROR_IMAGES_REPOSITORY/$BUILD_DIRECTORY"
    DOCKER_IMAGE_FQDN="$KANIKO_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITLAB_MIRROR_IMAGES_VERSION"
    DOCKER_IMAGE_FQDN_LATEST="$KANIKO_REGISTRY_HOSTNAME/$IMAGE_NAME:latest"
    echo "[INFO] Building $DOCKER_IMAGE_FQDN, $DOCKER_IMAGE_FQDN_LATEST"
    /kaniko/executor $KANIKO_REGISTRY_PUSH_FLAGS --context ./$BUILD_DIRECTORY --dockerfile ./$BUILD_DIRECTORY/Dockerfile --destination $DOCKER_IMAGE_FQDN --destination $DOCKER_IMAGE_FQDN_LATEST 
  
  - echo "[INFO] Pushed $DOCKER_IMAGE_FQDN_LATEST"
  - echo "[INFO] Pushed $DOCKER_IMAGE_FQDN"

git-force-push-remote-branch:
  <<: *kaniko-build-template
  variables:
    BUILD_DIRECTORY: "git-force-push-remote-branch"

git-force-push-remote-tag:
  <<: *kaniko-build-template
  variables:
    BUILD_DIRECTORY: "git-force-push-remote-tag"

git-pull-conventional-remote-branches:
  <<: *kaniko-build-template
  variables:
    BUILD_DIRECTORY: "git-pull-conventional-remote-branches"

git-zip-archive-mr-to-s3:
  <<: *kaniko-build-template
  variables:
    BUILD_DIRECTORY: "git-zip-archive-mr-to-s3"
  
    