#!/bin/sh
#
# When committing ... make sure script is executable (especially windows)
# > git update-index --chmod=+x pre-commit
#
# To activate copy into .git/hooks or use git config 
# > git config core.hooksPath hooks

# Redirect output to stderr.
exec 1>&2

###############
# 100MB Limit #
###############
CURRENT_DIR="$(pwd)"
HAS_ERROR=""

for file in $(git diff --cached --name-only | sort | uniq); do
	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
	if [ "$file_size" -ge 100 ]; then
		echo "$file is over 100MB."
		HAS_ERROR="1"
	fi
done

if [ "$HAS_ERROR" != "" ]; then
    echo "Can't commit, fix errors first." >&2
    exit 1
fi

exit 0